// Abreviações e gírias de internet em português → palavra base (já normalizada, sem acento)
// Aplicadas só à pergunta: o texto do guia é escrito por extenso.
// Termos do jogo (lvl, dex, boss...) ficam em src/data/guideAliases.ts
export const ABBREVIATIONS: Record<string, string> = {
  vc: "voce",
  vcs: "voces",
  ce: "voce",
  pq: "porque",
  q: "que",
  oq: "o que",
  oque: "o que",
  qm: "quem",
  ql: "qual",
  qnd: "quando",
  qdo: "quando",
  qndo: "quando",
  kd: "onde",
  cade: "onde",
  ond: "onde",
  ondi: "onde",
  cm: "como",
  cmo: "como",
  n: "nao",
  nn: "nao",
  tb: "tambem",
  tbm: "tambem",
  td: "tudo",
  tds: "todos",
  mt: "muito",
  mto: "muito",
  mtt: "muito",
  msm: "mesmo",
  hj: "hoje",
  agr: "agora",
  dps: "depois",
  dpois: "depois",
  aq: "aqui",
  ngm: "ninguem",
  cmg: "comigo",
  d: "de",
  p: "para",
  c: "com",
  eh: "e",
  ta: "esta",
  to: "estou",
  tava: "estava",
  vo: "vou",
  fzr: "fazer",
  fz: "faz",
  blz: "beleza",
  vlw: "valeu",
  obg: "obrigado",
  obgd: "obrigado",
  brigadao: "obrigado",
  flw: "falou",
  eae: "e ai",
  eai: "e ai",
  iae: "e ai",
  pf: "por favor",
  pfv: "por favor",
  pls: "por favor",
  plz: "por favor",
};
